version: 2.1
jobs:
  test:
    executor: node/default
    steps:
    - run:
        name: Check that the files in the events and enums folders are defined correctly
        command: cd todo-mvc && npm run publish

workflows:
  build:
    jobs:
    - test
