---
version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
  test:
    executor: node/default
    working_directory: ~/project
    parameters:
      tag:
        default: ''
        description: If it exists, then the version with the tag will be released to the production environment
        type: string
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          command: ./deploy.sh "<< parameters.tag >>"
workflows:
  build:
    jobs:
      - test
