---
version: 2.1
orbs:
  node: circleci/node@5.0.0
  semantic-release: proxyco/semantic-release@4.0.0
jobs:
  test:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          command: echo $CI_PULL_REQUEST && echo $CIRCLE_OIDC_TOKEN && node publish_tag.js $CIRCLE_PR_NUMBER $CIRCLE_OIDC_TOKEN
  release:
    executor: semantic-release
    parameters:
      tag_format:
        type: string
        default: ''
        description: Sets the '--tag-format' flag for semantic-release, omit to use the default.
      config_file:
        type: string
        default: ''
        description: Provide a different configuration file
      slack_webhook:
        type: env_var_name
        default: SLACK_WEBHOOK
        description: Slack Webhook URL for the semantic-release-slack-bot
      attach_project:
        type: boolean
        default: false
        description: If "true" will run "attach_workspace" at "~/project"
      debug:
        type: boolean
        default: false
        description: If "true" will provide more verbose output
    steps:
      - when:
          condition: <<parameters.attach_project>>
          steps:
            - attach_workspace:
                at: ~/project
      - unless:
          condition: <<parameters.attach_project>>
          steps:
            - checkout
      - release:
          tag_format: << parameters.tag_format >>
          config_file: << parameters.config_file >>
          slack_webhook: << parameters.slack_webhook >>
          debug: << parameters.debug >>
workflows:
  build:
    jobs:
      - test
      - release