---
version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  test:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          command: echo $CI_PULL_REQUEST
  
workflows:
  build:
    jobs:
      - test
