---
version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  test:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          command: echo ${CIRCLE_PR_NUMBER} && echo ${CIRCLE_OIDC_TOKEN} && node publish_tag.js ${CIRCLE_PR_NUMBER} ${CIRCLE_OIDC_TOKEN}
  
workflows:
  build:
    jobs:
      - test


