---
version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
  test:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          command: echo ${GITHUB_TOKEN} && echo ${CIRCLE_PROJECT_USERNAME} && echo ${CIRCLE_PROJECT_REPONAME} && echo ${CIRCLE_SHA1} && echo ${VERSION} 
workflows:
  build:
    jobs:
      - test
