---
version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
  test:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          command: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/project
workflows:
  build:
    jobs:
      - test
