version: 2.1
orbs: 
  node: circleci/node@5.0.0

jobs:
  test:
    executor: node/default
    working_directory: ~/project
    steps:
    - checkout
    - node/install-packages:
        cache-path: ./node_modules
        override-ci-command: npm install
    - run:
        command: npm run test
  publish:
    executor: node/default
    working_directory: ~/project
    steps:
    - checkout
    - node/install-packages:
        cache-path: ./node_modules
        override-ci-command: npm install
    - run:
        command: npm run publish
  run-pwd:
    executor: node/default
    working_directory: ~/project
    steps:
    - checkout
    - node/install-packages:
        cache-path: ./node_modules
        override-ci-command: npm install
    - run:
        command: pwd
  run-ll:
    executor: node/default
    working_directory: ~/project
    steps:
    - checkout
    - node/install-packages:
        cache-path: ./node_modules
        override-ci-command: npm install
    - run:
        command: ls -l
  test-branch:
    executor: node/default
    working_directory: ~/project
    steps:
    - checkout
    - node/install-packages:
        cache-path: ./node_modules
        override-ci-command: npm install
    - run:
        command: echo 'staging'
  test-label:
    executor: node/default
    working_directory: ~/project
    steps:
    - checkout
    - node/install-packages:
        cache-path: ./node_modules
        override-ci-command: npm install
    - run:
        command: echo 'approve'


workflows:
  build:
    jobs:
    - test
    - publish
  where_are_you:
    jobs:
    - run-pwd
    - run-ll
    - test-label:
        type: approval
    - test-branch:
        filters:
          branches:
            only: 
              - staging

