version: 2.1
orbs: 
  node: circleci/node@5.0.0

jobs:
  test:
    executor: node/default
    working_directory: ~/project
    steps:
    - checkout
    - node/install-packages:
        cache-path: ./node_modules
        override-ci-command: npm install
    - run:
        name: Check that the files in the events and enums folders are defined correctly
        command: pwd && ls -l && npm run publish

workflows:
  build:
    jobs:
    - test
